sudo: required
dist: bionic
before_script:
    - sudo apt-get -q update
    - sudo apt-get install -y swig cppcheck wget python3-virtualenv clang-format-9
    - wget -P /tmp/ https://raw.githubusercontent.com/torvalds/linux/184b8f7f91ca7938c09533df83ce84817e682975/scripts/checkpatch.pl && chmod a+x /tmp/checkpatch.pl
    - wget -P /tmp/ https://raw.githubusercontent.com/torvalds/linux/184b8f7f91ca7938c09533df83ce84817e682975/scripts/spelling.txt
    - wget -P /tmp/ https://raw.githubusercontent.com/torvalds/linux/184b8f7f91ca7938c09533df83ce84817e682975/scripts/const_structs.checkpatch
script:
    - wget -P https://launchpad.net/ubuntu/+archive/primary/+files/codespell_1.17.1-1_all.deb
    - sudo dpkg -i codespell_1.17.1-1_all.deb
    - make cppcheck
    - make style CHECKPATCH=/tmp/checkpatch.pl CLANGFORMAT=clang-format-9
    - make
    - sudo make install
    - LD_LIBRARY_PATH=`pwd`/lib make -C lib/python test
    - LD_LIBRARY_PATH=`pwd`/lib make -C appqos test
    - cd lib/perl && perl Makefile.PL && make && sudo make install
language: c
compiler:
    - gcc
#    - clang
